#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gimp
Version  : 2.8.20
Release  : 7
URL      : https://download.gimp.org/mirror/pub/gimp/v2.8/gimp-2.8.20.tar.bz2
Source0  : https://download.gimp.org/mirror/pub/gimp/v2.8/gimp-2.8.20.tar.bz2
Summary  : GIMP Library
Group    : Development/Tools
License  : BSD-3-Clause GPL-2.0 GPL-3.0 LGPL-3.0
Requires: gimp-bin
Requires: gimp-lib
Requires: gimp-data
Requires: gimp-doc
Requires: gimp-locales
BuildRequires : alsa-lib-dev
BuildRequires : automake
BuildRequires : automake-dev
BuildRequires : bzip2-dev
BuildRequires : docbook-xml
BuildRequires : gdk-pixbuf
BuildRequires : gegl-dev
BuildRequires : gettext
BuildRequires : gettext-bin
BuildRequires : gtk+
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : intltool
BuildRequires : libjpeg-turbo-dev
BuildRequires : libtool
BuildRequires : libtool-dev
BuildRequires : libxml2-dev
BuildRequires : libxslt-bin
BuildRequires : m4
BuildRequires : perl(XML::Parser)
BuildRequires : pkg-config-dev
BuildRequires : pkgconfig(atk)
BuildRequires : pkgconfig(babl)
BuildRequires : pkgconfig(cairo)
BuildRequires : pkgconfig(cairo-pdf)
BuildRequires : pkgconfig(dbus-glib-1)
BuildRequires : pkgconfig(fontconfig)
BuildRequires : pkgconfig(gdk-pixbuf-2.0)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(gmodule-no-export-2.0)
BuildRequires : pkgconfig(gtk+-2.0)
BuildRequires : pkgconfig(gudev-1.0)
BuildRequires : pkgconfig(iso-codes)
BuildRequires : pkgconfig(lcms2)
BuildRequires : pkgconfig(libcurl)
BuildRequires : pkgconfig(libexif)
BuildRequires : pkgconfig(libpng)
BuildRequires : pkgconfig(librsvg-2.0)
BuildRequires : pkgconfig(pangocairo)
BuildRequires : pkgconfig(xcursor)
BuildRequires : pkgconfig(xfixes)
Patch1: 0001-stateless-conversion.patch

%description
------------------------------
GNU Image Manipulation Program
2.8 Stable Branch
------------------------------


%package bin
Summary: bin components for the gimp package.
Group: Binaries
Requires: gimp-data

%description bin
bin components for the gimp package.


%package data
Summary: data components for the gimp package.
Group: Data

%description data
data components for the gimp package.


%package dev
Summary: dev components for the gimp package.
Group: Development
Requires: gimp-lib
Requires: gimp-bin
Requires: gimp-data
Provides: gimp-devel

%description dev
dev components for the gimp package.


%package doc
Summary: doc components for the gimp package.
Group: Documentation

%description doc
doc components for the gimp package.


%package lib
Summary: lib components for the gimp package.
Group: Libraries
Requires: gimp-data

%description lib
lib components for the gimp package.


%package locales
Summary: locales components for the gimp package.
Group: Default

%description locales
locales components for the gimp package.



%prep
%setup -q -n gimp-2.8.20
%patch1 -p1
pushd ..
cp -a gimp-2.8.20 avx2
popd

%build
export LANG=C
export SOURCE_DATE_EPOCH=1491964716
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto -fno-semantic-interposition "
%reconfigure --disable-static --without-libtiff --disable-python --enable-sse
make V=1  %{?_smp_mflags}
pushd ../avx2/
export CFLAGS="$CFLAGS -mavx2 -mfma"
export CXXFLAGS="$CXXFLAGS  -mavx2 -mfma"
export LDFLAGS="$LDFLAGS  -mavx2 -mfma"
%reconfigure --disable-static --without-libtiff --disable-python --enable-sse  --libdir=/usr/lib64/avx2
make V=1  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1491964716
rm -rf %{buildroot}
pushd ../avx2/
%make_install
popd

%make_install
%find_lang gimp20
%find_lang gimp20-libgimp
%find_lang gimp20-python
%find_lang gimp20-script-fu
%find_lang gimp20-std-plug-ins
%find_lang gimp20-tips
 
%files
%defattr(-,root,root,-)
/usr/lib64/gimp/2.0/environ/default.env
/usr/lib64/gimp/2.0/interpreters/default.interp
/usr/lib64/gimp/2.0/plug-ins/*

%files bin
%defattr(-,root,root,-)
/usr/bin/gimp
/usr/bin/gimp-2.8
/usr/bin/gimp-console
/usr/bin/gimp-console-2.8
/usr/bin/gimptool-2.0

%files data
%defattr(-,root,root,-)
/usr/share/appdata/gimp.appdata.xml
/usr/share/applications/gimp.desktop
/usr/share/defaults/gimp/2.0/controllerrc
/usr/share/defaults/gimp/2.0/gimprc
/usr/share/defaults/gimp/2.0/gtkrc
/usr/share/defaults/gimp/2.0/menurc
/usr/share/defaults/gimp/2.0/sessionrc
/usr/share/defaults/gimp/2.0/templaterc
/usr/share/defaults/gimp/2.0/unitrc
/usr/share/gimp/2.0/brushes/*
/usr/share/gimp/2.0/dynamics/*
/usr/share/gimp/2.0/fractalexplorer/*
/usr/share/gimp/2.0/gfig/*
/usr/share/gimp/2.0/gimpressionist/*
/usr/share/gimp/2.0/gradients/*
/usr/share/gimp/2.0/images/*
/usr/share/gimp/2.0/menus/*
/usr/share/gimp/2.0/palettes/*
/usr/share/gimp/2.0/patterns/*
/usr/share/gimp/2.0/scripts/*
/usr/share/gimp/2.0/themes/*
/usr/share/gimp/2.0/tool-presets/*
/usr/share/gimp/2.0/ui/*
/usr/share/icons/*
/usr/share/gimp/2.0/gflare/Bright_Star
/usr/share/gimp/2.0/gflare/Classic
/usr/share/gimp/2.0/gflare/Default
/usr/share/gimp/2.0/gflare/Distant_Sun
/usr/share/gimp/2.0/gflare/GFlare_101
/usr/share/gimp/2.0/gflare/GFlare_102
/usr/share/gimp/2.0/gflare/Hidden_Planet
/usr/share/gimp/2.0/tags/gimp-tags-default.xml
/usr/share/gimp/2.0/tips/gimp-tips.xml


%files dev
%defattr(-,root,root,-)
/usr/include/gimp-2.0/*
/usr/lib64/libgimp-2.0.so
/usr/lib64/libgimpbase-2.0.so
/usr/lib64/libgimpcolor-2.0.so
/usr/lib64/libgimpconfig-2.0.so
/usr/lib64/libgimpmath-2.0.so
/usr/lib64/libgimpmodule-2.0.so
/usr/lib64/libgimpthumb-2.0.so
/usr/lib64/libgimpui-2.0.so
/usr/lib64/libgimpwidgets-2.0.so
/usr/lib64/pkgconfig/gimp-2.0.pc
/usr/lib64/pkgconfig/gimpthumb-2.0.pc
/usr/lib64/pkgconfig/gimpui-2.0.pc
/usr/share/aclocal/*.m4

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
%doc /usr/share/man/man5/*
/usr/share/gtk-doc/html/*


%files lib
%defattr(-,root,root,-)
/usr/lib64/gimp/2.0/modules/libcolor-selector-cmyk.so
/usr/lib64/gimp/2.0/modules/libcolor-selector-water.so
/usr/lib64/gimp/2.0/modules/libcolor-selector-wheel.so
/usr/lib64/gimp/2.0/modules/libcontroller-linux-input.so
/usr/lib64/gimp/2.0/modules/libcontroller-midi.so
/usr/lib64/gimp/2.0/modules/libdisplay-filter-color-blind.so
/usr/lib64/gimp/2.0/modules/libdisplay-filter-gamma.so
/usr/lib64/gimp/2.0/modules/libdisplay-filter-high-contrast.so
/usr/lib64/gimp/2.0/modules/libdisplay-filter-lcms.so
/usr/lib64/gimp/2.0/modules/libdisplay-filter-proof.so
/usr/lib64/libgimp-2.0.so.0
/usr/lib64/libgimp-2.0.so.0.800.20
/usr/lib64/libgimpbase-2.0.so.0
/usr/lib64/libgimpbase-2.0.so.0.800.20
/usr/lib64/libgimpcolor-2.0.so.0
/usr/lib64/libgimpcolor-2.0.so.0.800.20
/usr/lib64/libgimpconfig-2.0.so.0
/usr/lib64/libgimpconfig-2.0.so.0.800.20
/usr/lib64/libgimpmath-2.0.so.0
/usr/lib64/libgimpmath-2.0.so.0.800.20
/usr/lib64/libgimpmodule-2.0.so.0
/usr/lib64/libgimpmodule-2.0.so.0.800.20
/usr/lib64/libgimpthumb-2.0.so.0
/usr/lib64/libgimpthumb-2.0.so.0.800.20
/usr/lib64/libgimpui-2.0.so.0
/usr/lib64/libgimpui-2.0.so.0.800.20
/usr/lib64/libgimpwidgets-2.0.so.0
/usr/lib64/libgimpwidgets-2.0.so.0.800.20
/usr/lib64/avx2/

%files locales -f gimp20.lang -f gimp20-libgimp.lang -f gimp20-python.lang -f gimp20-script-fu.lang -f gimp20-std-plug-ins.lang -f gimp20-tips.lang
%defattr(-,root,root,-)
